ID=0
variableName=numOfReplicas
className=org.apache.hadoop.hdfs.server.blockmanagement.BlockPlacementPolicyDefault
lineNumber=525
methodName=chooseRandom
parameterTypes=int,java.lang.String,java.util.Set,long,int,java.util.List,boolean,org.apache.hadoop.hdfs.StorageType
strategy=after