ID=0
strategy=after
className=org.apache.hadoop.hdfs.server.blockmanagementBlockPlacementPolicyDefault
methodName=chooseRandom
parameterTypes=int,java.lang.String,java.util.Set,long,int,java.util.List,boolean,org.apache.hadoop.hdfs.StorageType
lineNumber=533
byteCodeIndex=188
variableName=numOfReplicas
