ID=1
variableName=numOfReplicas
lineNumber=ENTRY
className=org.apache.hadoop.hdfs.server.blockmanagementBlockPlacementPolicyDefault
methodName=chooseRandom
parameterTypes=int,java.lang.String,java.util.Set,long,int,java.util.List,boolean,org.apache.hadoop.hdfs.StorageType
