ID=1
variableName=i
variableName=storages
className=org.apache.hadoop.hdfs.server.blockmanagement.BlockPlacementPolicyDefault
methodName=chooseRandom
parameterTypes=int,java.lang.String,java.util.Set,long,int,java.util.List,boolean,org.apache.hadoop.hdfs.StorageType
lineNumber=524
byteCodeIndex=154
