ID=3
variableName=numOfAvailableNodes
className=org.apache.hadoop.hdfs.server.blockmanagement.BlockPlacementPolicyDefault
lineNumber=511
methodName=chooseRandom
parameterTypes=int,java.lang.String,java.util.Set,long,int,java.util.List,boolean,org.apache.hadoop.hdfs.StorageType
