ID=-35
className=org.apache.hadoop.hbase.util.HBaseFsck
methodName=getOrCreateInfo
lineNumber=ENTRY
byteCodeIndex=-1
strategy=stackTrace
parameterTypes=
variableName=foo
parameterTypes=java.lang.String

