ID=-4
className=org.apache.hadoop.hbase.util.HBaseFsck$1
methodName=processRow
lineNumber=ENTRY
byteCodeIndex=-1
strategy=stackTrace
parameterTypes=org.apache.hadoop.hbase.client.Result
variableName=foo
