ID=0
variableName=Foo
className=org.matrix.android.sdk.internal.session.sync.DefaultSyncTask
methodName=downloadInitSyncResponse
parameterTypes=java.util.Map,org.matrix.android.sdk.internal.session.sync.DefaultSyncTask$SyncStatisticsData,kotlin.coroutines.Continuation
lineNumber=213
byteCodeIndex=399

