ID=-4
className=org.apache.hadoop.security.token.delegation.AbstractDelegationTokenSecretManager
methodName=addPersistedDelegationToken
parameterTypes=org.apache.hadoop.security.token.delegation.AbstractDelegationTokenIdentifier,long
lineNumber=ENTRY
byteCodeIndex=-1
strategy=stackTrace
variableName=foo
