ID=1
strategy=before
className=org.apache.hadoop.security.token.delegation.AbstractDelegationTokenSecretManager
methodName=storeToken
parameterTypes=org.apache.hadoop.security.token.delegation.AbstractDelegationTokenIdentifier,org.apache.hadoop.security.token.delegation.AbstractDelegationTokenSecretManager$DelegationTokenInformation
lineNumber=287
byteCodeIndex=4
variableName=foo
