ID=4
strategy=before
className=org.apache.hadoop.security.token.delegation.AbstractDelegationTokenSecretManager
methodName=addPersistedDelegationToken
parameterTypes=org.apache.hadoop.security.token.delegation.AbstractDelegationTokenIdentifier,long
lineNumber=328
byteCodeIndex=132
variableName=foo
