ID=5
strategy=before
className=org.apache.hadoop.security.token.delegation.AbstractDelegationTokenSecretManager
methodName=cancelToken
parameterTypes=org.apache.hadoop.security.token.Token,java.lang.String
lineNumber=566
byteCodeIndex=222
variableName=foo
