ID=1111
strategy=conditional
className=org.apache.hadoop.security.token.delegation.AbstractDelegationTokenSecretManager
methodName=checkToken
parameterTypes=
lineNumber=429
byteCodeIndex=55
variableName=foo

# DelegationTokenInformation info = currentTokens.get(identifier);
# if (info == null) {
# 429   throw new InvalidToken("token (" + identifier.toString()
#       + ") can't be found in cache");
# }