ID=-1
variableName=Foo
className=org.matrix.android.sdk.internal.session.sync.handler.room.RoomSyncHandler
methodName=handleTimelineEvents
parameterTypes=io.realm.Realm,java.lang.String,org.matrix.android.sdk.internal.database.model.RoomEntity,java.util.List,java.lang.String,boolean,org.matrix.android.sdk.internal.database.model.EventInsertType,long,org.matrix.android.sdk.internal.session.sync.SyncResponsePostTreatmentAggregator
lineNumber=ENTRY
byteCodeIndex=-1
strategy=stackTrace

