ID=-2
className=org.apache.hadoop.security.token.delegation.AbstractDelegationTokenSecretManager
methodName=getTokenInfo
parameterTypes=org.apache.hadoop.security.token.delegation.AbstractDelegationTokenIdentifier
lineNumber=ENTRY
byteCodeIndex=-1
strategy=stackTrace
variableName=foo
