ID=2
strategy=before
className=org.apache.hadoop.security.token.delegation.AbstractDelegationTokenSecretManager
methodName=getTokenInfo
parameterTypes=org.apache.hadoop.security.token.delegation.AbstractDelegationTokenIdentifier
lineNumber=277
byteCodeIndex=4
variableName=foo
