ID=6
strategy=before
className=org.apache.hadoop.security.token.delegation.AbstractDelegationTokenSecretManager
methodName=removeExpiredToken
parameterTypes=
lineNumber=626
byteCodeIndex=80
variableName=foo
