ID=1
variableName=numOfReplicas
lineNumber=ENTRY
byteCodeIndex=0
className=org.apache.hadoop.hdfs.server.blockmanagement.BlockPlacementPolicyDefault
methodName=chooseRandom
parameterTypes=int,java.lang.String,java.util.Set,long,int,java.util.List,boolean,org.apache.hadoop.hdfs.StorageType
