ID=4
variableName=NetworkTopology_chooseRandom_839a2c427bed5cc5b86a77e9bcc401a43761c505
className=org.apache.hadoop.hdfs.server.blockmanagement.BlockPlacementPolicyDefault
methodName=chooseRandom
parameterTypes=int,java.lang.String,java.util.Set,long,int,java.util.List,boolean,org.apache.hadoop.hdfs.StorageType
lineNumber=518
byteCodeIndex=127
