ID=0
strategy=stackTrace
className=org.apache.hadoop.hdfs.server.blockmanagement.BlockPlacementPolicyDefault
methodName=addIfIsGoodTarget
parameterTypes=org.apache.hadoop.hdfs.server.blockmanagement.DatanodeStorageInfo, java.util.Set, long, int, boolean, java.util.List, boolean, org.apache.hadoop.hdfs.StorageType
lineNumber=ENTRY
byteCodeIndex=-1
variableName=BlockPlacementPolicyDefault_isGoodTarget_a48297ce2b560e1c08f53d16a260b9af7414ffd4
