ID=2
className=org.apache.hadoop.hdfs.server.blockmanagement.BlockPlacementPolicyDefault
methodName=addIfIsGoodTarget
parameterTypes=org.apache.hadoop.hdfs.server.blockmanagement.DatanodeStorageInfo, java.util.Set, long, int, boolean, java.util.List, boolean, org.apache.hadoop.hdfs.StorageType
lineNumber=567
byteCodeIndex=16
variableName=BlockPlacementPolicyDefault_addToExcludedNodes_2828cb492b93a38e2eb9700389500e740bc98e76
