ID=11
strategy=beforeReturn
className=org.apache.hadoop.hdfs.server.blockmanagement.BlockPlacementPolicyDefault
methodName=isGoodTarget
parameterTypes=org.apache.hadoop.hdfs.server.blockmanagement.DatanodeStorageInfo, long, int, boolean, java.util.List, boolean, org.apache.hadoop.hdfs.StorageType
lineNumber=654
byteCodeIndex=223
variableName=BlockPlacementPolicyDefault_logNodeIsNotChosen_772ba6df1918160cfb9230511812cdb9c5bd319d
