ID=-24
className=org.apache.hadoop.hdfs.server.blockmanagement.DatanodeDescriptor
methodName=decrementBlocksScheduled
parameterTypes=
lineNumber=ENTRY
byteCodeIndex=-2
strategy=stackTrace
variableName=now
