ID=-21
className=org.apache.hadoop.hdfs.server.blockmanagement.DatanodeDescriptor
methodName=rollBlocksScheduled
parameterTypes=long
lineNumber=ENTRY
byteCodeIndex=-2
strategy=stackTrace
variableName=now
