ID=0
strategy=logCutting
className=org.apache.hadoop.hdfs.server.blockmanagement.BlockPlacementPolicyDefault
methodName=chooseRandom
parameterTypes=java.lang.String,java.util.Set,long,int,java.util.List,boolean,org.apache.hadoop.hdfs.StorageType
lineNumber=-1
byteCodeIndex=-1
variableName=foo
