ID=1
strategy=logCutting
className=org.apache.hadoop.hdfs.server.blockmanagement.BlockPlacementPolicyDefault
methodName=chooseRemoteRack
parameterTypes=int,org.apache.hadoop.hdfs.server.blockmanagement.DatanodeDescriptor,java.util.Set,long,int,java.util.List,boolean,org.apache.hadoop.hdfs.StorageType
lineNumber=-1
byteCodeIndex=-1
variableName=foo
