ID=2
strategy=logCutting
className=org.apache.hadoop.hdfs.server.blockmanagement.BlockPlacementPolicyDefault
methodName=chooseTarget
parameterTypes=int,org.apache.hadoop.net.Node,java.util.Set,long,int,java.util.List,boolean,org.apache.hadoop.hdfs.StorageType
lineNumber=-1
byteCodeIndex=-1
variableName=foo
