ID=0
strategy=logCutting
className=org.apache.hadoop.hdfs.server.blockmanagement.BlockManager$ReplicationWork
methodName=chooseTargets
parameterTypes=org.apache.hadoop.hdfs.server.blockmanagement.BlockPlacementPolicy,java.util.Set
lineNumber=-1
byteCodeIndex=-1
variableName=foo
