ID=1
strategy=logCutting
className=org.apache.hadoop.hdfs.server.blockmanagement.BlockPlacementPolicyDefault
methodName=chooseTarget
parameterTypes=java.lang.String,int,org.apache.hadoop.net.Node,java.util.Set,long,java.util.List,org.apache.hadoop.hdfs.StorageType
lineNumber=-1
byteCodeIndex=-1
variableName=foo