ID=7
variableName=Foo
className=org.matrix.android.sdk.internal.database.helper.TimelineEventEntityHelperKt
methodName=isMoreRecentThan
parameterTypes=org.matrix.android.sdk.internal.database.model.TimelineEventEntity,org.matrix.android.sdk.internal.database.model.TimelineEventEntity
lineNumber=34
byteCodeIndex=33