ID=3
strategy=before
className=org.apache.hadoop.yarn.server.resourcemanager.scheduler.fair.policies.ComputeFairShares
methodName=resourceUsedWithWeightToResourceRatio
parameterTypes=double,java.util.Collection,org.apache.hadoop.yarn.server.resourcemanager.resource.ResourceType
lineNumber=194
byteCodeIndex=47
variableName=foo
#istore 4
