ID=-2
strategy=stackTrace
className=org.apache.hadoop.yarn.server.resourcemanager.resource.ResourceWeights
methodName=ResourceWeights
parameterTypes=
lineNumber=ENTRY
byteCodeIndex=-1
variableName=foo
