ID=0
strategy=before
className=org.apache.cassandra.db.Columns$Serializer
methodName=deserialize
parameterTypes=org.apache.cassandra.io.util.DataInputPlus,org.apache.cassandra.config.CFMetaData
lineNumber=443
byteCodeIndex=61
variableName=foo
