ID=2
strategy=before
className=org.apache.cassandra.db.Columns$Serializer
methodName=deserialize
parameterTypes=org.apache.cassandra.io.util.DataInputPlus,org.apache.cassandra.config.CFMetaData
lineNumber=437
byteCodeIndex=48
variableName=foo
