ID=-1
className=org.apache.zookeeper.server.quorum.CommitProcessor
methodName=needCommit
lineNumber=ENTRY
byteCodeIndex=-1
strategy=stackTrace
variableName=foo
parameterTypes=org.apache.zookeeper.server.Request
