ID=1
className=org.apache.zookeeper.server.quorum.CommitProcessor
methodName=needCommit
lineNumber=132
byteCodeIndex=1
strategy=conditional
variableName=foo
parameterTypes=org.apache.zookeeper.server.Request
