ID=1111
className=org.apache.zookeeper.server.ZKDatabase
methodName=addCommittedProposal
parameterTypes=org.apache.zookeeper.server.Request
lineNumber=252
byteCodeIndex=103
strategy=conditional
variableName=foo
