ID=2
className=org.apache.zookeeper.server.quorum.CommitProcessor
methodName=processCommitted
parameterTypes=
lineNumber=233
byteCodeIndex=127
variableName=foo

#     123: aload_0
#        124: getfield      #17                 // Field nextPending:Ljava/util/concurrent/atomic/AtomicReference;
#        127: aconst_null
#        128: invokevirtual #36                 // Method java/util/concurrent/atomic/AtomicReference.set:(Ljava/lang/Object;)V
#        131: aload_0
#        132: aload_2
