
ID=2
className=org.apache.zookeeper.server.Request
methodName=Request
lineNumber=ENTRY
byteCodeIndex=-1
strategy=stackTrace
parameterTypes=long,int,int,org.apache.zookeeper.txn.TxnHeader,org.apache.jute.Record,long
variableName=foo

