ID=-1
variableName=Foo
className=org.matrix.android.sdk.internal.database.query.ReadQueriesKt
methodName=isBeforeLatestReadReceipt
parameterTypes=org.matrix.android.sdk.internal.database.model.TimelineEventEntity,io.realm.Realm,java.lang.String,java.lang.String,java.lang.String
lineNumber=ENTRY
byteCodeIndex=-1
strategy=stackTrace
