ID=1
className=org.apache.hadoop.hdfs.protocol.DatanodeInfo
methodName=DatanodeInfo
parameterTypes=org.apache.hadoop.hdfs.protocol.DatanodeInfo
lineNumber=91
byteCodeIndex=43
variableName=foo
strategy=before_print
