ID=10
variableName=Foo
className=im.vector.app.features.notifications.OutdatedEventDetector
methodName=isMessageOutdated
parameterTypes=im.vector.app.features.notifications.NotifiableEvent
lineNumber=38
byteCodeIndex=80

