ID=-1
className=org.apache.hadoop.security.token.delegation.AbstractDelegationTokenSecretManager
methodName=storeToken
parameterTypes=org.apache.hadoop.security.token.delegation.AbstractDelegationTokenIdentifier,org.apache.hadoop.security.token.delegation.AbstractDelegationTokenSecretManager$DelegationTokenInformation
lineNumber=ENTRY
byteCodeIndex=-1
strategy=stackTrace
variableName=foo
