ID=5
className=org.apache.hadoop.hbase.zookeeper.ZKUtil
methodName=getDataNoWatch
parameterTypes=org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher,java.lang.String,org.apache.zookeeper.data.Stat
lineNumber=588
byteCodeIndex=19
variableName=foo
