ID=-4
className=org.apache.zookeeper.server.DataTree
methodName=deleteNode
parameterTypes=java.lang.String,byte[],java.util.List,long,long,long
lineNumber=Entry
byteCodeIndex=-1
strategy=stackTrace
variableName=path
