ID=3
className=org.apache.zookeeper.server.DataTree
methodName=createNode
parameterTypes=java.lang.String,byte[],java.util.List,long,long,long
lineNumber=Entry
byteCodeIndex=-1
strategy=before
variableName=path
