ID=3
className=org.apache.hadoop.hdfs.server.blockmanagement.HeartbeatManager$Stats
methodName=add
parameterTypes=org.apache.hadoop.hdfs.server.blockmanagement.DatanodeDescriptor
lineNumber=410
byteCodeIndex=23
variableName=foo
strategy=before_print