ID=6
className=org.apache.hadoop.hdfs.server.blockmanagement.HeartbeatManager$Stats
methodName=subtract
parameterTypes=org.apache.hadoop.hdfs.server.blockmanagement.DatanodeDescriptor
lineNumber=427
byteCodeIndex=23
variableName=foo
strategy=before_print