ID=3
className=org.apache.hadoop.hdfs.protocol.DatanodeInfo
methodName=DatanodeInfo
parameterTypes=org.apache.hadoop.hdfs.protocol.DatanodeID
lineNumber=107
byteCodeIndex=34
variableName=foo
strategy=before_print