ID=-3
className=org.apache.hadoop.hdfs.server.blockmanagement.BlockInfo
methodName=BlockInfo
parameterTypes=org.apache.hadoop.hdfs.protocol.Block,short
lineNumber=entry
byteCodeIndex=-1
variableName=foo
strategy=stackTrace