ID=2
className=org.apache.hadoop.hdfs.server.blockmanagement.BlockInfo
methodName=BlockInfo
parameterTypes=org.apache.hadoop.hdfs.protocol.Block,short
lineNumber=88
byteCodeIndex=19
variableName=foo
strategy=stackTrace