ID=-1
variableName=foo
className=im.vector.app.core.di.ActiveSessionHolder
methodName=getOrInitializeSession
parameterTypes=boolean,kotlin.coroutines.Continuation
lineNumber=ENTRY
byteCodeIndex=-1
strategy=stackTrace