ID=7
variableName=startSync
className=im.vector.app.core.di.ActiveSessionHolder
methodName=getOrInitializeSession
parameterTypes=boolean,kotlin.coroutines.Continuation
lineNumber=105
byteCodeIndex=16

