ID=1111
variableName=it.syncService().isSyncThreadAlive()
className=im.vector.app.core.di.ActiveSessionHolder
methodName=getOrInitializeSession
parameterTypes=boolean,kotlin.coroutines.Continuation
lineNumber=106
byteCodeIndex=36
strategy=conditional

