ID=3
variableName=Foo
className=org.matrix.android.sdk.internal.database.query.ReadQueriesKt
methodName=isEventRead
parameterTypes=io.realm.RealmConfiguration,java.lang.String,java.lang.String,java.lang.String,boolean
lineNumber=1
byteCodeIndex=225

