ID=24
className=rg.apache.hadoop.hdfs.server.namenode.INodeDirectory
methodName=getExistingPathINodes
parameterTypes=byte[][],org.apache.hadoop.hdfs.server.namenode.INode[],boolean
lineNumber=186
byteCodeIndex=88
variableName=foo
