ID=28
className=rg.apache.hadoop.hdfs.server.namenode.INodeDirectory
methodName=getExistingPathINodes
parameterTypes=byte[][],org.apache.hadoop.hdfs.server.namenode.INode[],boolean
lineNumber=206
byteCodeIndex=309
variableName=foo
