ID=-1
variableName=Foo
className=im.vector.app.features.notifications.NotifiableEventProcessor
methodName=process
parameterTypes=java.util.List,java.lang.String,java.lang.String,java.util.List
lineNumber=ENTRY
byteCodeIndex=-1

