ID=-1
className=java.util.concurrent.atomic.AtomicReference
methodName=get
lineNumber=ENTRY
byteCodeIndex=-1
strategy=stackTrace
variableName=foo
# 
#   public final V get();
#     descriptor: ()Ljava/lang/Object;
#     flags: (0x0011) ACC_PUBLIC, ACC_FINAL
#     Code:
#       stack=1, locals=1, args_size=1
#          0: aload_0
#          1: getfield      #2                  // Field value:Ljava/lang/Object;
#          4: areturn
#       LineNumberTable:
#         line 85: 0
#     Signature: #43                          // ()TV;
# 
