ID=1
className=org.apache.zookeeper.server.quorum.CommitProcessor
methodName=processCommitted
parameterTypes=
lineNumber=220
byteCodeIndex=57
strategy=afterCall
variableName=foo
#
#   line 212: 42
#        line 220: 53
#        line 221: 64
#        line 226: 91
#        line 227: 99
#       52: astore_1
#        53: aload_0
#        54: getfield      #17                 // Field nextPending:Ljava/util/concurrent/atomic/AtomicReference;
#        57: invokevirtual #25                 // Method java/util/concurrent/atomic/AtomicReference.get:()Ljava/lang/Object;
#        60: checkcast     #34                 // class org/apache/zookeeper/server/Request
#        63: astore_2
