ID=2
className=java.util.concurrent.atomic.AtomicReference
methodName=set
lineNumber=java.lang.Object
byteCodeIndex=2
variableName=foo

#   public final void set(V);
#     descriptor: (Ljava/lang/Object;)V
#     flags: (0x0011) ACC_PUBLIC, ACC_FINAL
#     Code:
#       stack=2, locals=2, args_size=2
#          0: aload_0
#          1: aload_1
#          2: putfield      #2                  // Field value:Ljava/lang/Object;
#          5: return
#       LineNumberTable:
#         line 94: 0
#         line 95: 5
#     Signature: #39                          // (TV;)V
# 
