ID=3
className=org.apache.zookeeper.server.quorum.CommitProcessor
methodName=run
parameterTypes=
lineNumber=173
byteCodeIndex=124
variableName=foo
#         line 173: 120 
#        121: getfield      #17                 // Field nextPending:Ljava/util/concurrent/atomic/AtomicReference;
#        124: aload_1
#        125: invokevirtual #36                 // Method java/util/concurrent/atomic/AtomicReference.set:(Ljava/lang/Object;)V
