ID=1
className=org.apache.zookeeper.server.Request
methodName=Request
lineNumber=43
byteCodeIndex=52
parameterTypes=org.apache.zookeeper.server.ServerCnxn,long,int,int,java.nio.ByteBuffer,java.util.List
variableName=foo
#  36 public class Request {
#  37     public final static Request requestOfDeath = new Request(null, 0, 0, 0, null, null);
#  38 
#  39     public Request(ServerCnxn cnxn, long sessionId, int xid, int type, ByteBuffer bb, List<Id> authInfo) {
#  40         this.cnxn = cnxn;
#  41         this.sessionId = sessionId;
#  42         this.cxid = xid;
#  43         this.type = type;
#  44         this.request = bb;
#  45         this.authInfo = authInfo;
#  46     }
#  47 
#  48     public Request(long sessionId, int xid, int type, TxnHeader hdr, Record txn, long zxid) {
#  49         this.sessionId = sessionId;
#  50         this.cxid = xid;
#  51         this.type = type;
#  52         this.hdr = hdr;
#  53         this.txn = txn;
#  54         this.zxid = zxid;
#  55         this.request = null;
#  56         this.cnxn = null;
#  57         this.authInfo = null;
#  58     }
#  59 
