ID=1111
className=org.apache.zookeeper.ZooKeeperMain
methodName=processZKCmd
parameterTypes=org.apache.zookeeper.ZooKeeperMain$MyCommandOptions
lineNumber=729
byteCodeIndex=1207
strategy=conditional
variableName=foo
