ID=-1
strategy=stackTrace
className=org.apache.hadoop.yarn.server.resourcemanager.scheduler.fair.policies.ComputeFairShares
methodName=computeShare
parameterTypes=org.apache.hadoop.yarn.server.resourcemanager.scheduler.fair.Schedulable,double,org.apache.hadoop.yarn.server.resourcemanager.resource.ResourceType
lineNumber=ENTRY
byteCodeIndex=-1
variableName=min
