ID=1
strategy=
className=org.apache.hadoop.yarn.server.resourcemanager.scheduler.fair.policies.ComputeFairShares
methodName=computeShare
parameterTypes=org.apache.hadoop.yarn.server.resourcemanager.scheduler.fair.Schedulable,double,org.apache.hadoop.yarn.server.resourcemanager.resource.ResourceType
lineNumber=207
byteCodeIndex=49
variableName=min
