ID=-4
strategy=stackTrace
className=org.apache.hadoop.yarn.server.resourcemanager.resource.ResourceWeights
methodName=setWeight
parameterTypes=org.apache.hadoop.yarn.server.resourcemanager.resource.ResourceType,float
lineNumber=ENTRY
byteCodeIndex=-1
variableName=resourceType
