ID=-1
strategy=stackTrace
className=org.apache.hadoop.yarn.server.resourcemanager.resource.ResourceWeights
methodName=ResourceWeights
parameterTypes=float
lineNumber=ENTRY
byteCodeIndex=-1
variableName=foo
