ID=-6
className=org.apache.hadoop.hdfs.server.blockmanagement.HeartbeatManager$Stats
methodName=subtract
parameterTypes=org.apache.hadoop.hdfs.server.blockmanagement.DatanodeDescriptor
lineNumber=ENTRY
byteCodeIndex=-1
variableName=foo
strategy=stackTrace