ID=30
className=org.apache.hadoop.hdfs.server.blockmanagement.HeartbeatManager$Stats
methodName=add
parameterTypes=org.apache.hadoop.hdfs.server.blockmanagement.DatanodeDescriptor
lineNumber=entry
byteCodeIndex=-1
variableName=foo
strategy=stackTrace