ID=-1
className=org.apache.hadoop.hdfs.protocol.DatanodeInfo
methodName=DatanodeInfo
parameterTypes=org.apache.hadoop.hdfs.protocol.DatanodeID
lineNumber=entry
byteCodeIndex=-1
variableName=foo
strategy=stackTrace