ID=10
className=org.apache.hadoop.hdfs.protocol.DatanodeInfo
methodName=DatanodeInfo
parameterTypes=org.apache.hadoop.hdfs.protocol.DatanodeInfo
lineNumber=entry
byteCodeIndex=-1
variableName=foo
strategy=stackTrace