ID=-28
className=org.apache.hadoop.hdfs.server.blockmanagement.DatanodeDescriptor
methodName=incrementBlocksScheduled
parameterTypes=
lineNumber=ENTRY
byteCodeIndex=-2
strategy=stackTrace
variableName=now
