ID=3
strategy=before
className=org.apache.cassandra.db.Columns$Serializer
methodName=deserialize
parameterTypes=org.apache.cassandra.io.util.DataInputPlus,org.apache.cassandra.config.CFMetaData
lineNumber=433
byteCodeIndex=29
variableName=foo
