ID=-4
strategy=stackTrace
className=org.apache.cassandra.config.CFMetaData
methodName=CFMetaData
parameterTypes=java.lang.String,java.lang.String,java.util.UUID,boolean,boolean,boolean,boolean,boolean,java.util.List,java.util.List,org.apache.cassandra.db.PartitionColumns,org.apache.cassandra.dht.IPartitioner
lineNumber=ENTRY
byteCodeIndex=-2
variableName=this