ID=5
strategy=before
className=org.apache.cassandra.config.CFMetaData
methodName=addOrReplaceColumnDefinition
parameterTypes=org.apache.cassandra.config.ColumnDefinition
lineNumber=ENTRY
byteCodeIndex=-1
variableName=def
