ID=7
variableName=Foo
className=im.vector.app.core.di.ActiveSessionHolder
methodName=getOrInitializeSession
parameterTypes=boolean,kotlin.coroutines.Continuation
lineNumber=4294967295
byteCodeIndex=16

