ID=1
variableName=Foo
className=org.matrix.android.sdk.internal.database.helper.ChunkEntityHelperKt
methodName=nextDisplayIndex
parameterTypes=org.matrix.android.sdk.internal.database.model.ChunkEntity, org.matrix.android.sdk.internal.session.room.timeline.PaginationDirection
lineNumber=166
byteCodeIndex=28
strategy=conditional
