ID=1
className=org.apache.hadoop.hdfs.server.datanode.DataNode
methodName=DataNode
parameterTypes=org.apache.hadoop.conf.Configuration,java.util.AbstractList,org.apache.hadoop.hdfs.server.datanode.SecureDataNodeStarter$SecureResources
lineNumber=202
byteCodeIndex=22
variableName=foo