ID=-1
strategy=stackTrace
className=org.apache.cassandra.db.Columns$Serializer
methodName=deserialize
parameterTypes=org.apache.cassandra.io.util.DataInputPlus,org.apache.cassandra.config.CFMetaData
lineNumber=ENTRY
byteCodeIndex=-1
variableName=foo
