ID=3
strategy=before
className=org.apache.cassandra.config.CFMetaData
methodName=removeColumnDefinition
parameterTypes=org.apache.cassandra.config.ColumnDefinition
lineNumber=ENTRY
byteCodeIndex=-1
variableName=def