ID=15
className=org.apache.hadoop.hbase.zookeeper.ZKUtil
methodName=getDataNoWatch
parameterTypes=org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher,java.lang.String,org.apache.zookeeper.data.Stat
lineNumber=592
byteCodeIndex=58
variableName=foo
