ID=1111
variableName=Foo
className=org.matrix.android.sdk.internal.session.sync.handler.room.RoomSyncHandler
methodName=deleteLocalEchosIfNeeded
parameterTypes=org.matrix.android.sdk.internal.database.model.EventInsertType,org.matrix.android.sdk.internal.database.model.RoomEntity,java.util.List
lineNumber=642
byteCodeIndex=176
strategy=conditional

