ID=-1
className=org.apache.zookeeper.server.DataTree
methodName=addDataNode
parameterTypes=java.lang.String,org.apache.zookeeper.server.DataNode
lineNumber=Entry
byteCodeIndex=-1
strategy=stackTrace
variableName=path
