ID=-17
className=rg.apache.hadoop.hdfs.server.namenode.INodeDirectory
methodName=getExistingPathINodes
parameterTypes=byte[][],org.apache.hadoop.hdfs.server.namenode.INode[],boolean
lineNumber=ENTRY
byteCodeIndex=-1
strategy=stackTrace
variableName=foo
