ID=17
className=rg.apache.hadoop.hdfs.server.namenode.INodeDirectory
methodName=getExistingPathINodes
parameterTypes=byte[][],org.apache.hadoop.hdfs.server.namenode.INode[],boolean
lineNumber=191
byteCodeIndex=133
variableName=foo
