ID=1111
className=rg.apache.hadoop.hdfs.server.namenode.INodeDirectory
methodName=getExistingPathINodes
parameterTypes=byte[][],org.apache.hadoop.hdfs.server.namenode.INode[],boolean
strategy=conditional
lineNumber=204
byteCodeIndex=298
variableName=foo
