ID=4
strategy=beforeReturn
className=org.apache.hadoop.hdfs.server.blockmanagement.BlockPlacementPolicyDefault
methodName=isGoodTarget
parameterTypes=org.apache.hadoop.hdfs.server.blockmanagement.DatanodeStorageInfo, long, int, boolean, java.util.List, boolean, org.apache.hadoop.hdfs.StorageType
lineNumber=626
byteCodeIndex=82
variableName=DatanodeInfo_getNetworkLocation_0587228a0ebf615358fede09151b8afc31ab9d86
variableName=String_equals_951b4dc388763a53473bf39dd2f3d308fc60450a
#return false