ID=32
className=org.apache.hadoop.hdfs.protocol.DatanodeInfo
methodName=DatanodeInfo
parameterTypes=java.lang.String,java.lang.String,java.lang.String,int,int,int,int,long,long,long,long,long,long,long,int,java.lang.String,org.apache.hadoop.hdfs.protocol.DatanodeInfo$AdminStates
lineNumber=ENTRY
byteCodeIndex=-1
variableName=remaining
